
for dir in $(ls -d eval/abx/result/exp/hybrid_onehot/*/*flabel*{b16,onehot}*post/*/analysis); do
    # fix_timit_abx_csv
    # make the csv files generated by ABX test agree with their score file
    sed -re '26897 s/^(.*)4/\11/' \
	-e '83656 s/^(.*)4/\11/' \
	-e '147285 s/^(.*)4/\11/' \
	-e '402787 s/^(.*)4/\11/' \
	-e '530385 s/^(.*)4/\11/' \
	-e '540503 s/^(.*)4/\11/' \
	-e '1614767 s/^(.*)4/\11/' \
	-e '1637013 s/^(.*)4/\11/' \
	-e '1646491 s/^(.*)4/\11/' $dir/timit_across.csv > $dir/timit_across.csv.fix

    # paste <(cat $dir/timit_within.csv | sed '1 d' | awk '{for(i=0; i<$6; i++) print}') <(cat $dir/tmp/within_triplet_score.txt) |  awk '{printf "%s\t%s\t%s%s\t%s\n", $1, $2, $3, $4, $7}' | sed '1 i phone_2\tphone_1\tcontext\tscore' > $dir/tmp/timit_within_full.csv

    paste <(cat $dir/timit_within.csv | sed '1 d' | awk '{for(i=0; i<$6; i++) print}') <(cat $dir/tmp/within_triplet_score.txt) |  awk '{printf "%s\t%s\t%s%s\t%s\n", $1, $2, $3, $4, $7}'  | sed '1 i phone_2\tphone_1\ttalker\tcontext\tscore' | tr -d \'\(\) | tr , '\t' > $dir/tmp/timit_within_full.csv

    # paste <(cat $dir/timit_across.csv.fix | sed '1 d' | awk '{for(i = 0; i < $7; ++i) print}') <(cat $dir/tmp/across_triplet_score.txt) | sed '1 i talker_2\ttalker_1\tphone_2\tphone_1\tcontext\tscore\tn\tscore' | awk '{print $1, $2, $3, $4, $5, $8}' OFS="\t" > $dir/tmp/timit_across_full.csv
    paste <(cat $dir/timit_across.csv.fix | sed '1 d' | awk '{for(i = 0; i < $7; ++i) print}') <(cat $dir/tmp/across_triplet_score.txt) | sed '1 i talker_2\ttalker_1\tphone_2\tphone_1\tcontext\tscore\tn\tscore' | awk '{print $1, $2, $3, $4, $5, $8}' OFS="\t" | awk '{printf "%s_%s\t%s\n", $1, $2, $0}' | sed '1 s/talker_2_talker_1/talker_pair/' > $dir/tmp/timit_across_full.csv
done

# (base) [bin-wu@ahccsclm02 analysis]$ diff timit_across.csv timit_across.csv.fix 
# 26897c26897
# < FRAM1	FJRE0	l	m	ae-er	1.0	4
# ---
# > FRAM1	FJRE0	l	m	ae-er	1.0	1
# 83656c83656
# < MESD0	MDAB0	m	er	ay-s	1.0	4
# ---
# > MESD0	MDAB0	m	er	ay-s	1.0	1
# 147285c147285
# < MCCS0	MMDB1	iy	er	f-dx	1.0	4
# ---
# > MCCS0	MMDB1	iy	er	f-dx	1.0	1
# 402787c402787
# < MDSC0	FMML0	sil	er	jh-ih	1.0	4
# ---
# > MDSC0	FMML0	sil	er	jh-ih	1.0	1
# 530385c530385
# < MTAA0	MDWK0	er	l	ow-dx	1.0	4
# ---
# > MTAA0	MDWK0	er	l	ow-dx	1.0	1
# 540503c540503
# < MJES0	FLAS0	iy	n	r-aa	1.0	4
# ---
# > MJES0	FLAS0	iy	n	r-aa	1.0	1
# 1614767c1614767
# < MJAR0	MDBB0	l	r	t-ay	1.0	4
# ---
# > MJAR0	MDBB0	l	r	t-ay	1.0	1
# 1637013c1637013
# < MDSC0	MSTK0	w	s	uw-ow	1.0	4
# ---
# > MDSC0	MSTK0	w	s	uw-ow	1.0	1
# 1646491c1646491
# < MJBR0	MBPM0	aa	sil	z-f	1.0	4
# ---
# > MJBR0	MBPM0	aa	sil	z-f	1.0	1

# dir=eval/abx/result/exp/hybrid_onehot/ce/v2_timit_test_raw.vtln.cmvn.deltas.mfcc.dpmm.flabel.onehot.post_post/cos/analysis
# sed -n -re '26897 s/^(.*)4/\11/ p' \
#     -e '83656 s/^(.*)4/\11/ p' \
#     -e '147285 s/^(.*)4/\11/ p' \
#     -e '402787 s/^(.*)4/\11/ p' \
#     -e '530385 s/^(.*)4/\11/ p' \
#     -e '540503 s/^(.*)4/\11/ p' \
#     -e '1614767 s/^(.*)4/\11/ p' \
#     -e '1637013 s/^(.*)4/\11/ p' \
#     -e '1646491 s/^(.*)4/\11/ p' $dir/timit_across.csv

# dir=eval/abx/result/exp/hybrid_onehot/ce/v2_timit_test_raw.vtln.cmvn.deltas.mfcc.dpmm.flabel.onehot.post_post/cos/analysis
# sed -n -re '26897 s/^(.*)4/\11/ p' \
#     -e '83656 s/^(.*)4/\11/ p' \
#     -e '147285 s/^(.*)4/\11/ p' \
#     -e '402787 s/^(.*)4/\11/ p' \
#     -e '530385 s/^(.*)4/\11/ p' \
#     -e '540503 s/^(.*)4/\11/ p' \
#     -e '1614767 s/^(.*)4/\11/ p' \
#     -e '1637013 s/^(.*)4/\11/ p' \
#     -e '1646491 s/^(.*)4/\11/ p' $dir/timit_across.csv
